### PR TITLE
Minor tutorial updates (from PyCascades sprint)

### PR DESCRIPTION
**Pull request by ltirrell**
This PR includes minor updates and fixes to the tutorials, found during the PyCascades sprint when learning about Bokeh:

- Add a link in each notebook to go to the next tutorial in the series, or go back to the overview page
- Remove the background from the "Bokeh Tutorial" image at the top of each nb (when using dark mode in Jupyter, the old image just showed up as white rectangle)
- Replace http://bokeh.org with https://bokeh.org in all notebooks (for consistency)
- Fix any broken links or typos that I noticed:
  - Notably, in the [Datashader notebook](tutorial/A2 - Visualizing Big Data with Datashader.ipynb), I changed the link since it seems the project has moved?
- Updated the command in `CONTRIBUTING.md` so that it can handle whitespace in filenames
- Added `jupyter_contrib_nbextensions` to the environment, since this seems like it was required to run the required command in `CONTRIBUTING.md`

I went through the first 3 tutorial notebooks in more detail, fixing more typos and links that seemed to point to the wrong location. I plan on doing that for the other notebooks in the near future. Should that be in another PR, or added to this one?

P.S. Would it be useful setting up something like [ReviewNB](https://www.reviewnb.com/) to more easily compare diffs of notebooks (free for open source)? It removes metadata diffs, and renders NBs side-by-side

### CODE REVIEW

**Comment by bryevdv** [comment]
@ltirrell This is fantastic, happy to merge this now and have follow-on PRs or keep adding to this PR, really up to you. 

> P.S. Would it be useful setting up something like ReviewNB to more easily compare diffs of notebooks (free for open source)? It removes metadata diffs, and renders NBs side-by-side

Seems like it would be amazing. Not sure how it would do with actual Bokeh plot content but even still for everything else. I will look in to getting it installed with our service account.

**Comment by ltirrell** [comment]
@bryevdv maybe it'd be better to merge this now, and I'll do a follow up (probably over the weekend). 

Regarding ReviewNB, I added it to my fork and did an example PR just to see how it worked. It doesn't render the bokeh plots, and isn't perfect (the diff of the "Bokeh Tutorial" image HTML looks weird, for example), but it seems to catch all the changes and would definitely be easier to review/add comments using that interface. 

Here's the [link](https://app.reviewnb.com/ltirrell/bokeh-notebooks/pull/1/) if you want to check it out, I think a login is required though.

**Comment by bryevdv** [comment]
Thanks for your contribution @ltirrell !

**Comment by bryevdv** [comment]
Also I have installed ReviewNB on this repo. Does it automatically offer any link on PRs or do you just need to know to go check it?

**Comment by ltirrell** [comment]
Awesome, thanks!

ReviewNB should auto-post a comment with a review link after new PRs are created (this is [my example](https://github.com/ltirrell/bokeh-notebooks/pull/1#issuecomment-585454103).

**Pull request merged**
