### PR TITLE
Fixing loop variable naming to avoid overwriting the existing one

### PR DESCRIPTION
**Pull request by bsipocz**
The list comprehension was causing an error as x was overwritten.

### CODE REVIEW

**Comment by bsipocz** [comment]
Apparently the example worked in python3, but not in python2, changing the name of the variable fix it in python2, too.

**Comment by mattpap** [comment]
Nice:
```
$ python3 -c 'x = [1,2,3]; [10 - x for x in x]; print(x)'
[1, 2, 3]
$ python2 -c 'x = [1,2,3]; [10 - x for x in x]; print(x)'
3
```
Who would expect that?

**Comment by mattpap** [comment]
LGTM

**Comment by bsipocz** [comment]
To be honest it was a big surprise for me that it worked in python3 like that (obviously I haven't switched yet...)

**Comment by damianavila** [comment]
Interesting... let's get this merged

**Pull request merged**
